name: Coding Standards

on:
  push:
  pull_request:
  schedule:
    - cron: '25 9 * * 4'

jobs:
  ecs:
    name: ECS - PHP ${{ matrix.php }} Ubuntu

    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
        dependencies:
          - 'highest'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Run Easy Coding Standard
        run: |
          php -d memory_limit=-1 -d zend.enable_gc=0 -d error_reporting=-1 vendor/bin/ecs --ansi --no-progress-bar;
        env:
          PHP_VERSION: ${{ matrix.php }}
